name: Deploy workflow for Obsrv-API

on:
  push:
    branches:
    - actions-build
    
jobs:
  docker:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2


    - name: Run docker file
      run: |
        docker run -f Dockerfile